CREATE TABLE `services` (
	`id` INT(9) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' ENGINE=MyISAM AUTO_INCREMENT=7 ;

CREATE TABLE `discounts` (
	`id` INT(9) NOT NULL AUTO_INCREMENT,
	`percent` INT(3) NULL DEFAULT NULL,
	`services` VARCHAR(500) NULL DEFAULT NULL,
	`birthday_before` INT(11) NULL DEFAULT NULL,
	`birthday_after` INT(11) NULL DEFAULT NULL,
	`phone` VARCHAR(10) NULL DEFAULT NULL,
	`gender` VARCHAR(5) NULL DEFAULT NULL,
	`date_start` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`date_end` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`)
) COLLATE='utf8_general_ci' ENGINE=MyISAM ;
